import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { NavbarSimpleColored } from '../components/Navbar/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavbarSimpleColored />
      </main>
    </div>
  )
}

export default Home
